# Generated by Django 5.1.4 on 2025-01-06 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_autor_lesson_autor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Введите текст вопроса', verbose_name='Текст вопроса')),
                ('image', models.ImageField(blank=True, help_text='Добавьте изображение', null=True, upload_to='users_tests/images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Введите текст ответа', verbose_name='Текст ответа')),
                ('image', models.ImageField(blank=True, help_text='Добавьте изображение', null=True, upload_to='users_tests/images', verbose_name='Изображение')),
                ('is_correct', models.BooleanField(blank=True, default=False, help_text='Отметьте, если ответ правильный', null=True, verbose_name='Правильность ответа')),
                ('question', models.ManyToManyField(help_text='Укажите для какого вопроса этот ответ', to='users_tests.question', verbose_name='Ответ на вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответ',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название теста', max_length=150, verbose_name='Название тест')),
                ('instruction', models.TextField(blank=True, help_text='Добавьте инструкцию к тесту', null=True, verbose_name='Инструкция к тесту')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор теста')),
                ('course', models.ForeignKey(blank=True, help_text='Выберите курс, к которому относится тест', null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс, к которому относится тест')),
                ('lesson', models.ForeignKey(blank=True, help_text='Выберите урок, к которому относится тест', null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='Урок, к которому относится тест')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ManyToManyField(help_text='Укажите для какого теста этот вопрос', to='users_tests.test', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=300, verbose_name='Ответ пользователя')),
                ('attempt', models.IntegerField(default=0, verbose_name='Номер попытки')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Правильность ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_tests.question', verbose_name='На какой вопрос этот ответ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
    ]
