# Generated by Django 5.1.4 on 2025-01-12 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(blank=True, help_text='Укажите для какого теста этот вопрос', null=True, on_delete=django.db.models.deletion.CASCADE, to='users_tests.test', verbose_name='Тест'),
        ),
    ]
