# Generated by Django 5.1.4 on 2025-01-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Добавьте название курса', max_length=300, verbose_name='Название курса')),
                ('description', models.TextField(blank=True, help_text='Добавьте описание курса', null=True, verbose_name='Описание курса')),
                ('status', models.CharField(choices=[('available', 'доступен'), ('unavailable', 'недоступен'), ('in progress', 'в процессе'), ('passed', 'пройден')], default='available', max_length=16, verbose_name='Статус курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
